from typing import Literal
from loguru import logger
from langgraph.types import Command
from langgraph.graph.state import CompiledStateGraph
from langchain_core.messages import AIMessage, HumanMessage

from app.core.prompts.executor_prompts import EXECUTOR_INNER_QUERY_PROMPT
from app.utils.observability.tracing import tracing
from app.common.constants import ObservationType, PlanStatus
from app.core.graph.state.planner_state import AgentStepObservation, PlanExecuteState
from app.core.graph.nodes.agent_graph_node import AgentGraphNode
from app.utils.graph.context_utils import get_recent_messages

def make_executor_node(inner_react_graph: CompiledStateGraph):
    """Wraps existing ReAct Agent as a sub-graph."""

    @tracing(observation_type=ObservationType.CHAIN)
    async def executor(state: PlanExecuteState) -> Command[
        Literal[AgentGraphNode.OUTER_SYNTHESIZER, AgentGraphNode.EXECUTOR]
    ]:
        plan = state.get("plan", [])
        past_steps = state.get("past_steps", [])

        # 1. Find the next pending step
        current_step = next((step for step in plan if step.status == PlanStatus.PENDING), None)
        
        if not current_step:
            logger.warning("⚠️ [Executor] No pending steps found. Proceeding to exit.")
            return Command(
                goto=AgentGraphNode.OUTER_SYNTHESIZER,
                update={"plan": plan}
            )
        
        logger.info(f"⚙️ [Executor] Running Step {current_step.step_id} of {len(plan)}: {current_step.description}")

        # 2. Build context from past steps to feed to the ReAct agent
        history_context = ""
        for obs in past_steps:
            history_context += f"Step {obs.step_id}: {obs.summary}\n"

        inner_query = EXECUTOR_INNER_QUERY_PROMPT.format(
            step_description=current_step.description,
            history_context=history_context
        )

        # 3. Create a fresh INNER state for your ReAct Agent
        recent_messages = get_recent_messages(state.get("messages", []), last_k_turns=3)

        inner_state_input = {
            "query": current_step.description,
            "messages": recent_messages + [HumanMessage(content=inner_query)],
            "active_project": state.get("active_project"), 
            "active_datasets": state.get("active_datasets", []),
            "system_datasets": state.get("system_datasets", []),
            "summary": state.get("summary", ""),
            "past_steps": past_steps,
            "execution_id": state.get("execution_id"),

            "rag_results": state.get("rag_results", []),
            "tool_results": state.get("tool_results", []),
            "web_results": state.get("web_results", [])
        }

        # 4. Run the Inner Agent
        inner_result = {}
        hard_failure = False
        try:
            inner_result = await inner_react_graph.ainvoke(inner_state_input)
            step_answer = inner_result.get("final_answer", "No answer generated by inner agent.")
            extracted_data = inner_result.get("extracted_knowledge", [])

            # Only mark COMPLETED if the inner agent confirms success
            is_inner_complete = inner_result.get("is_complete", False)

            if is_inner_complete:
                final_status = PlanStatus.COMPLETED
                logger.info(f"✅ [Executor] Step {current_step.step_id} completed successfully.")
            else:
                final_status = PlanStatus.FAILED
                logger.warning(f"⚠️ [Executor] Step {current_step.step_id} could not find all required information. Continuing plan.")

        except Exception as e:
            logger.error(f"❌ [Executor] Inner agent crashed on step {current_step.step_id}: {e}")
            step_answer = f"Error executing step: {str(e)}"
            extracted_data = []
            final_status = PlanStatus.FAILED
            hard_failure = True

        # 5. Save Observation and mark Step status
        observation = AgentStepObservation(
            step_id=current_step.step_id,
            summary=step_answer
        )

        updated_plan = []
        for step in plan:
            if step.step_id == current_step.step_id:
                updated_step = step.model_copy(update={"status": final_status})
                updated_plan.append(updated_step)
            else:
                updated_plan.append(step)

        # 6. DYNAMIC ROUTING
        has_pending_steps = any(step.status == PlanStatus.PENDING for step in updated_plan)

        # Only break the loop on hard failures (exceptions). Soft failures (missing info)
        # still have partial results, so continue to remaining steps.
        if hard_failure:
            logger.error(f"[Executor] Step {current_step.step_id} HARD FAILED. Breaking loop.")
            destination = AgentGraphNode.OUTER_SYNTHESIZER
        elif has_pending_steps:
            destination = AgentGraphNode.EXECUTOR
        else:
            destination = AgentGraphNode.OUTER_SYNTHESIZER

        return Command(
            goto=destination,
            update={
                "plan": updated_plan,
                "past_steps": past_steps + [observation], 
                # "extracted_knowledge": extracted_data,
                # Propagate the inner graph's final answer up to the outer graph so that Planner can see what the Executor actually did.
                "messages": [
                    AIMessage(
                        content=step_answer,
                        additional_kwargs={"execution_id": str(state.get("execution_id"))}
                    )
                ],
                "rag_results": inner_result.get("rag_results", []),
                "tool_results": inner_result.get("tool_results", []),
                "web_results": inner_result.get("web_results", [])
            }
        )

    return executor
