from typing import Literal
from loguru import logger
from langgraph.types import Command
from langgraph.graph.state import CompiledStateGraph
from langchain_core.messages import HumanMessage

from app.core.prompts.executor_prompts import EXECUTOR_INNER_QUERY_PROMPT
from app.utils.observability.tracing import tracing
from app.common.constants import ObservationType, PlanStatus
from app.core.graph.state.planner_state import AgentStepObservation, PlanExecuteState
from app.core.graph.nodes.agent_graph_node import AgentGraphNode

def make_executor_node(inner_react_graph: CompiledStateGraph):
    """Wraps existing ReAct Agent as a sub-graph."""

    @tracing(observation_type=ObservationType.CHAIN)
    async def executor(state: PlanExecuteState) -> Command[
        Literal[AgentGraphNode.SUMMARIZER, AgentGraphNode.EXECUTOR]
    ]:
        plan = state.get("plan", [])
        past_steps = state.get("past_steps", [])

        # 1. Find the next pending step
        current_step = next((step for step in plan if step.status == PlanStatus.PENDING), None)
        
        if not current_step:
            logger.warning("⚠️ [Executor] No pending steps found. Proceeding to exit.")
            return Command(
                goto=AgentGraphNode.SUMMARIZER,
                update={"plan": plan}
            )

        logger.info(f"⚙️ [Executor] Running Step {current_step.step_id}: {current_step.description}")

        # 2. Build context from past steps to feed to the ReAct agent
        history_context = ""
        for obs in past_steps:
            history_context += f"Step {obs.step_id}: {obs.summary}\n"

        inner_query = EXECUTOR_INNER_QUERY_PROMPT.format(
            step_description=current_step.description,
            history_context=history_context
        )

        # 3. Create a fresh INNER state for your ReAct Agent
        inner_state_input = {
            # Step 
            "query": current_step.description,
            "messages": [HumanMessage(content=inner_query)],

            # Inner Circuit Breaker
            "iteration_count": 0,
            "max_iterations": 5,

            # Global context
            "active_project": state.get("active_project"), 
            "active_datasets": state.get("active_datasets", []),
            "summary": state.get("summary", ""),

            # Observability
            "execution_id": state.get("execution_id")
        }

        # 4. Run the Inner Agent
        try:
            inner_result = await inner_react_graph.ainvoke(inner_state_input)
            step_answer = inner_result.get("final_answer", "No answer generated by inner agent.")
            final_status = PlanStatus.COMPLETED
            
        except Exception as e:
            logger.error(f"❌ [Executor] Inner agent failed on step {current_step.step_id}: {e}")
            step_answer = f"Error executing step: {str(e)}"
            final_status = PlanStatus.FAILED

        # 5. Save Observation and mark Step Completed
        observation = AgentStepObservation(
            step_id=current_step.step_id,
            summary=step_answer
        )

        updated_plan = []
        for step in plan:
            if step.step_id == current_step.step_id:
                # .model_copy() guarantees LangGraph detects the state change
                updated_step = step.model_copy(update={"status": final_status})
                updated_plan.append(updated_step)
            else:
                updated_plan.append(step)

        # 6. DYNAMIC ROUTING: Check if there are any remaining pending steps
        has_pending_steps = any(step.status == PlanStatus.PENDING for step in updated_plan)
        
        if has_pending_steps:
            logger.info(f"[Executor] Step {current_step.step_id} marked as {final_status}. Looping back for next step.")
            destination = AgentGraphNode.EXECUTOR
        else:
            logger.info(f"[Executor] Step {current_step.step_id} marked as {final_status}. All steps complete, routing to Summarizer.")
            destination = AgentGraphNode.SUMMARIZER

        return Command(
            goto=destination,
            update={
                "plan": updated_plan,
                "past_steps": [observation] # operator.add will append this
            }
        )

    return executor