from typing import Literal
from loguru import logger
from langgraph.types import Command
from langgraph.graph.state import CompiledStateGraph
from langchain_core.messages import HumanMessage

from app.core.prompts.executor_prompts import EXECUTOR_INNER_QUERY_PROMPT
from app.utils.observability.tracing import tracing
from app.common.constants import ObservationType, PlanStatus
from app.core.graph.nodes.agent_planner import AgentStepObservation, PlanExecuteState
from app.core.graph.nodes.agent_graph_node import AgentGraphNode

def make_executor_node(inner_react_graph: CompiledStateGraph):
    """Wraps your existing LangGraph setup to execute a single step."""
    @tracing(observation_type=ObservationType.CHAIN)
    async def executor(state: PlanExecuteState) -> Command[Literal[AgentGraphNode.REPLANNER]]:
        plan = state.get("plan", [])
        past_steps = state.get("past_steps", [])

        # 1. Find the next pending step
        current_step = next((step for step in plan if step.status == PlanStatus.PENDING), None)
        
        if not current_step:
            logger.warning("⚠️ [Executor] No pending steps found, but routed here. Forwarding to replanner.")
            return Command(goto=AgentGraphNode.REPLANNER)

        logger.info(f"⚙️ [Executor] Running Step {current_step.step_id}: {current_step.description}")

        # 2. Build context from past steps to feed to the ReAct agent
        history_context = ""
        for obs in past_steps:
            history_context += f"Step {obs.step_id}: {obs.summary}\n"

        inner_query = EXECUTOR_INNER_QUERY_PROMPT.format(
            step_description=current_step.description,
            history_context=history_context
        )

        # 3. Create a fresh INNER state for your ReAct Agent
        inner_state_input = {
            "query": inner_query,
            "messages": [HumanMessage(content=inner_query)],
            "iteration_count": 0,
            # Inject global variables your inner graph needs
            "active_project_name": "Default", 
            "active_datasets": []
        }

        # 4. Await your existing Inner Graph
        inner_result = await inner_react_graph.ainvoke(inner_state_input)

        # 5. Extract the Synthesizer's final answer
        step_answer = inner_result.get("final_answer", "No answer generated by inner agent.")

        # 6. Save Observation and mark Step Completed
        observation = AgentStepObservation(
            step_id=current_step.step_id,
            summary=step_answer
        )

        updated_plan = []
        for step in plan:
            if step.step_id == current_step.step_id:
                step.status = PlanStatus.COMPLETED
            updated_plan.append(step)

        logger.debug(f"[Executor] Step {current_step.step_id} completed.")

        return Command(
            goto=AgentGraphNode.REPLANNER,
            update={
                "plan": updated_plan,
                "past_steps": [observation] # operator.add will append this
            }
        )

    return executor